services:
  app.api:
    image: app-api:latest
    build:
      context: .
      dockerfile: App.API/Dockerfile

  app2.api:
    image: app2-api:latest
    build:
      context: .
      dockerfile: App2.API/Dockerfile


  app3.api:
    image: app3-api:latest
    build:
      context: .
      dockerfile: App3.API/Dockerfile

