apiVersion: v1
kind: Service
metadata:
  name: app2-api
  namespace: app2-system
  labels:
    app.kubernetes.io/name: app2-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app2-api
  sessionAffinity: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
